Shops map
Delebrith/ShoppingM8-client pull request #45
Opened 2020-05-14 20:06 UTC by lychanl

Closes #41

2020-05-16 15:07 UTC, Delebrith commented on shoppingm8_fe/lib/list/product/productCategory.dart
> +        return { "bicycle store", "book store", "pet store", "electronics_store", "florist", "jewelry_store" };
just to be sure, is the lack of underscore intentional and does it work properly?

2020-05-18 14:19 UTC, lychanl commented on shoppingm8_fe/lib/list/product/productCategory.dart
> +        return { "bicycle store", "book store", "pet store", "electronics_store", "florist", "jewelry_store" };
Fixed

2020-05-18 19:11 UTC, Delebrith requested changes
I think a toast with short error message will be sufficient, but we need somehow tell the user if something goes wrong

2020-05-18 19:11 UTC, Delebrith commented on shoppingm8_fe/lib/maps/placesProvider.dart
> +      print("Error retrieving shops: " + (response.errorMessage ?? "null"));
maybe we should display an error message to the user besides logging it

2020-05-18 19:11 UTC, Delebrith commented on shoppingm8_fe/lib/maps/placesProvider.dart
> +      print("Failed to retrieve location");
the same thing

2020-05-19 13:45 UTC, Delebrith approved these changes

2020-05-19 13:45 UTC, merged